{
    "name": "PspMediaVolume",
    "version": "0.0.1",
    "icon": "fab fa-battle-net",
    "category": "undefined",
    "author": "poulsp",
    "maintainers": [],
    "desc": "Manage volume in the synchronous multiroom audio.",
    "aliceMinVersion": "1.0.0-b3",
    "systemRequirements": [
        ""
    ],
    "pipRequirements": [
        ""
    ],
    "conditions": {
        "lang": [
            "en"
        ],
        "online": true,
        "asrArbitraryCapture": true
    }
}